[package]
name = "day1-report-repair"
version = "0.1.0"
authors = ["rafaavc <rafavc2508@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
