[package]
name = "day6-custom-customs"
version = "0.1.0"
authors = ["rafaavc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
